cortex/src/cortex/util.cljc

https://github.com/mikera/core.matrix/issues/302

[util] Working around an exception coming from core.matrix:

---

compute/src/think/compute/nn/train.clj
cortex/src/cortex/dataset.clj
examples/suite-classification/LICENSE
examples/suite-classification/README.md
examples/suite-classification/project.clj
examples/suite-classification/src/suite_classification/core.clj
examples/suite-classification/src/suite_classification/main.clj
examples/suite-classification/train.sh
gpu-compute/project.clj
gpu-compute/src/think/compute/javacpp_datatype.clj
suite/.gitignore
suite/LICENSE
suite/README.md
suite/project.clj
suite/src/cortex/suite/classification.clj

Starting a suite subdirectory which will encapsulate the best practices and visual debugging for training various types of models.
* infinite dataset - specialized to make augmentation inline very easy and thus have infinite training data.
* classification model training & debugging.

Cortex suite

---

cortex/src/cortex/nn/network.clj

A function that given a network prints a nice summary of connections between layers and layer parameter buffer shapes.

[network/print-layer-summary] First cut.

---

examples/suite-classification/README.md

Update the example instructions to include the front end instructions too and update the port

Update example instructions with front end build commands

---

compute/project.clj
suite/project.clj

We have added better augmentation systems and a small bugfix (better errors) to think.datatype.

Upgrading default datatype and image libraries.

---

.travis.yml
examples/optimise/project.clj
examples/suite-classification/project.clj
importers/caffe/project.clj
importers/keras/project.clj
project.clj
scripts/Dockerfile
scripts/build-and-deploy.sh
scripts/build-and-test.sh
scripts/build-docker-and-test.sh
test/clj/cortex/compute/cuda_device_test.clj
test/clj/cortex/compute/cuda_optimize_test.clj
test/clj/cortex/compute/nn/cuda_gradient_test.clj
test/clj/cortex/compute/nn/cuda_layers_test.clj
test/clj/cortex/compute/nn/cuda_train_test.clj
test/clj/cortex/suite/logistic_test.clj

Tests are now passing on Travis.

[test] Limit some tests to do cpu-only so that things run on travis.

---

scripts/Dockerfile

Speed up the travis build by making the docker image slightly more minimal.

Speed up travis

---

src/cortex/nn/network.clj

We used to have this; just adding it back.

[network] Parameter count in table print.

---

experiment/src/cortex/experiment/train.clj
src/cortex/compute/verify/optimize.clj
src/cortex/nn/compute_binding.clj
src/cortex/nn/execute.clj
src/cortex/optimize.clj
src/cortex/optimize/adadelta.clj
src/cortex/optimize/adam.clj
src/cortex/verify/nn/train.clj

so the user has option of not restarting running parameters.

return optimizers from train

---

examples/docker-example/Dockerfile
examples/docker-example/README.md
examples/docker-example/project.clj
examples/docker-example/src/docker_example/core.clj
scripts/Dockerfile.cortex-base

Minimal docker base

---

src/cortex/compute/nn/backend.clj
src/cortex/verify/nn/train.clj
test/clj/cortex/compute/nn/cuda_train_test.clj
test/clj/cortex/compute/nn/train_test.clj

Testing that the network functions correctly in a multithreaded context.

Multithread test

---

src/cortex/nn/execute.clj
src/cortex/verify/nn/train.clj

The batch initialization code didn't finish before the upload process thus leading to interleaved init and initial buffer operation.

Tracked down one source of instability.

---

experiment/src/cortex/experiment/classification.clj
experiment/src/cortex/experiment/train.clj

Moving this forked branch to our repo for evaluation.

Stream eval metrics

---

experiment/project.clj
experiment/src/cortex/experiment/classification.clj
experiment/src/cortex/experiment/train.clj
experiment/test/cortex/experiment/logistic_test.clj
experiment/test/cortex/experiment/tensorboard_test.clj

Merging this into our repo for evaluation.

Tensorboard view

---

examples/catsdogs-classification/.gitignore
examples/catsdogs-classification/INTRO.md
examples/catsdogs-classification/build.boot
examples/catsdogs-classification/project.clj
examples/catsdogs-classification/src/catsdogs/prepare.clj
examples/catsdogs-classification/src/catsdogs/simple.clj
examples/catsdogs-classification/src/catsdogs/training.clj

Could that be added to the cortex examples?
I did not (cannot) put the images in the repository, so there is a manual step before hand, but the example is running pretty smoothly.
I also wrote a short introduction.

Adding cats dogs classification example

---

src/cortex/compute/cpu/backend.clj
src/cortex/compute/cuda/backend.clj
src/cortex/nn/impl.clj
src/cortex/nn/layers.clj
src/cortex/verify/nn/layers.clj
test/clj/cortex/compute/nn/cuda_layers_test.clj
test/clj/cortex/compute/nn/layers_test.clj

Made sure that they match the cudnn output which was reasonable.  Since we have a model coming in that will have a lot more edge cases we can wait till that model comes in and see if it passes verification.
@joycex99:  Let's make sure this passes travis tests and then I can push it into master.

avg pooling implemented and lightly tested them.

---

examples/xor-mlp/README.md
examples/xor-mlp/project.clj
examples/xor-mlp/src/xor_mlp/core.clj

Xor example

---

src/cortex/compute/cpu/tensor_math.clj
src/cortex/compute/cuda/tensor_math.clj
src/cortex/compute/nn/layers.clj
src/cortex/tensor.clj
src/cortex/tensor/math.clj
src/cortex/verify/tensor.clj

Added in fast paths for certain tensor operations to hit cudnn

Conv tensor perf issues

---

examples/resnet-retrain/src/resnet_retrain/core.clj
src/cortex/graph.clj
src/cortex/nn/execute.clj
src/cortex/tensor.clj
src/cortex/tensor/dimensions.clj

Major profiling wins in this work:
1.  Generalized select in the tensor opts is expensive.  Special cased out submatrix.
2.  Found and fixed a holding-onto-head issue reducing overall memory usage.
3.  The stream-augmentation system was broken up making loading data a lot faster.

Resnet50 profiling work

---

src/cortex/compute/array_view_math.clj
src/cortex/compute/cpu/backend.clj
src/cortex/compute/cpu/driver.clj
src/cortex/compute/cpu/tensor_math.clj
src/cortex/compute/cuda/backend.clj
src/cortex/compute/cuda/driver.clj
src/cortex/compute/cuda/tensor_math.clj
src/cortex/compute/math.clj
src/cortex/compute/nn/backend.clj
src/cortex/compute/nn/layers.clj
src/cortex/nn/layers.clj
src/cortex/tensor.clj
src/cortex/tensor/math.clj
src/cortex/verify/nn/layers.clj
src/cortex/verify/tensor.clj
test/clj/cortex/compute/cpu/tensor_test.clj
test/clj/cortex/compute/cuda/tensor_test.clj

dropout is implemented in terms of the tensor abstraction.

Tensor dropout

---

src/cortex/compute/nn/layers.clj

default value for :pool-op

---

src/cortex/compute/nn/layers.clj
src/cortex/nn/layers.clj

Multiplicative dropout typo

---

examples/resnet-retrain/README.md
examples/resnet-retrain/project.clj
examples/resnet-retrain/resize_images.sh
examples/resnet-retrain/src/resnet_retrain/core.clj

I finally got time to look at the RESNET50 retraining example.
Thank you! It's great and surprisingly, it actually ran an locally on my mac!
I went through the documentation and enhanced it with things I ran into. I also added some functions to test a pic and label it. 
There is another function I added to continue the training epoch by epoch, but would appreciate feedback if it is correct.
Hope this helps - and keep up the great work 💯

Resnet 50 Retrain example enhancements
