thinktopic/cortex

- datasets/src/cortex_datasets/math.clj
Following the first rule of Macro-club (Don't use macros !) I turned very-near? to a partial function application. 
No need for a macro to capture the global epsilon definition.
> Change very-near? to a function

- compute/src/think/compute/array_view_math.clj
- compute/src/think/compute/cpu_driver.clj
- compute/src/think/compute/datatype.clj
- compute/src/think/compute/math_util.clj
- compute/src/think/compute/nn/cpu_backend.clj
- gpu-compute/src/think/compute/cuda_driver.clj
Changed the underlying buffer representation for compute from nio buffers to array views.  
This will allow some greater compatibility with other clojure systems as they will also be backed by arrays at least in some cases (and will never be backed by nio buffers).  There may also be some perf benefit because arrays have native set/get methods while the nio buffer will always have a bit of a pathway *if* it is array backed.
> Non nio compute

- gpu-compute/src/think/compute/nn/cuda_backend.clj
These changes prevent the conv net from being too large which was occurring when an input size of 192x192 was used with several deep conv layers.
Not sure if this is what we want, but the changes are here to be looked at.
> [cuda] Limit the conv net sizes to support larger models.

- keras/export/create_combined_h5.py
- keras/export/get_keras_output.py
Improved model and some cleanup. This is opinionated in a way that changes the ingest pipeline:
* outputs per layer go into a sidecar h5 file.
* if we want layer descriptions/config in h5, go through the create_combined_h5.py (old name) script and generate the correct present version of the unified h5 model as per keras.
* guarantees aren't necessarily made for theano ordering. I think it's best to:
* make tensorflow weight and model generation the blessed path.
* if we want to munge between formats, use existing keras utilities or wrap them in our own script in a separate tool, e.g. a `th_to_tf.py`.
Some other comments:
* instead of rebuilding the model each time we use the keras backend function call that lets us generate the output by specifying the layer output we want by index.
* we …
> Keras scripts

- compute/src/think/compute/optimise.clj
I ran into a null pointer exception when I increased the batch size without increasing the number of samples. This, at the very least, gives better output -- though perhaps this could be checked at a higher location (and or handled more gracefully)?
> [optimize] Check inputs to evaluate-softmax.

- cortex/src/cortex/nn/network.cljc
In the network/train function, there's an unused epoch-count atom keeping track of the current epoch. Might be useful to print out the current epoch number when printing out that epoch's result.
> Print out epoch number when printing mse-loss

- compute/project.clj
- compute/src/think/compute/batching_system.clj
- compute/src/think/compute/nn/train.clj
- cortex/project.clj
- cortex/src/cortex/dataset.clj
- cortex/test/cljc/cortex/nn/scrabble_test.cljc
- examples/suite-classification/src/suite_classification/core.clj
- suite/src/cortex/suite/classification.clj
Large upgrade using new think.parallel features and enabling training on lower memory systems (albeit with higher gc usage).
1.  Change the batching and training system so that when doing inference we can pull out the labels from the dataset without needing to realize all the batches it separately from doing inference on them.  This was a difficult change but it makes doing work with a very large dataset a bit easier.
2.  Changed the infinite dataset definition such that the cross-validation, holdout, and training sets are sequences of epochs of data.  This allows, for instance, a clever implementation to produce cross-validation data on demand instead of pre-calculating it thus greatly reducing overall memory requirements.  
3.  Worked through the classification model and added a faster …
> Upgrade think parallel

- examples/suite-classification/src/suite_classification/core.clj
The image shape should be number of channels not the number of classes
> Fix typo in label-one example

- caffe/project.clj
- compute/project.clj
- cortex/project.clj
- datasets/project.clj
- gpu-compute/project.clj
- keras/project.clj
- suite/project.clj
- visualization/project.clj
just adding in codox for generating html docs.  
suite, visualization, and gpu-compute don't complete successfully.  With suite and gpu-compute that has to do with jnicuda, for instance:
java.lang.UnsatisfiedLinkError: no jnicuda in java.library.path, compiling:(think/compute/cuda_driver.clj:104:5)
visualization fails because it things m/add-outer-product! doesn't exist - codox may be pulling in the wrong version of core.matrix somehow.  
At any rate, the other five  projects succeed with lein codox.
> add codox plugin to projects

- caffe/src/caffe/core.clj
- compute/src/think/compute/nn/compute_execute.clj
- cortex/src/cortex/nn/layers.clj
- cortex/src/cortex/nn/network.clj
- cortex/src/cortex/nn/traverse.clj
- cortex/src/cortex/verify/nn/gradient.clj
- cortex/src/cortex/verify/nn/import.clj
- cortex/src/cortex/verify/nn/layers.clj
- cortex/src/cortex/verify/nn/train.clj
- cortex/test/clj/cortex/nn/network_test.clj
- cortex/test/clj/cortex/nn/traverse_test.clj
- keras/src/think/cortex/keras/core.clj
- suite/src/cortex/suite/classification.clj
- suite/src/cortex/suite/inference.clj
- suite/src/cortex/suite/train.clj
1.  Rename build.clj to network.clj
2.  Move the build-desc function into layers so that a layer can be defined completely in layers.clj.
3.  Move a few algorithms from compute_execute.clj up into respective locations in either network.clj or traverse.clj.
4.  Implement support for non-trainable parameters in network.clj and traverse.clj.
5.  Fix fallout from things like the system detecting a unit test has no trainable parameters and thus not creating buffers or a backward pass for it (and then the test failing).
> Non trainable parameters

- suite/src/cortex/suite/inference.clj
- gpu could never be used because of compote -> compute
- batch size was hard coded to `1`
- tiny improvement to a docstring.
> [suite/inference] Fix a few typos.

- README.md
The instructions in the README are a little confusing, saying to use CUDA-7.5 on master:
>  Current master is 7.5, if you're running 8.0 you will need to use the following branch
But then the instructions for OSX are for CUDA-8.0
> Update the OSX README instructions to use CUDA-7.5

- examples/suite-classification/README.md
- examples/suite-classification/src/suite_classification/main.clj
I took a closer look at https://github.com/thinktopic/cortex/pull/69 and recloned the repo and tried to run the example using `lein run`and found a problem with the web page displaying.
When the repo is cloned, there is just an empty resources directory https://github.com/thinktopic/cortex/tree/master/examples/suite-classification/resources.
Found that the assets never got generated and the webpage didn't show up because the main default is `train-forever-uberjar` https://github.com/thinktopic/cortex/blob/master/examples/suite-classification/src/suite_classification/main.clj#L7 which does not set the live-updates? to true to make the think.gate figwheel kick-off https://github.com/thinktopic/think.gate/blob/master/src/clj/think/gate/core.clj#L131
@harold once live-updates does get set to …
> Add an option to lein run to see the live-updates

- suite/src/cortex/suite/classification.clj
- suite/src/cortex/suite/train.clj
@cnuernber: "inferences" does not have the key ":output". The key seems to be the last node-id (like :softmax-1). Created a PR to highlight the issue -- other people using suite will encounter it on 0.4.0 and beyond.
> fixes the network-eval->cm bug

- cortex/src/cortex/nn/execute.clj
- cortex/src/cortex/verify/nn/train.clj
- suite/src/cortex/suite/train.clj
By passing `:simple-loss-print? true` to train-n, the user can get a one-line loss printout instead of the whole table. This is nice in many cases, including minimizing printout of unit tests that train lots of epochs fast.
> [suite/train] Simple loss print.

- src/cortex/datasets/mnist.clj
The site we were getting these from has been flaky. I put them on our s3 as public, hopefully that will be more reliable.
> [datasets/mnist] s3 > yann.

- src/cortex/verify/nn/train.clj
Re: https://github.com/thinktopic/cortex/issues/126
Recent refactors led to the mnist tests operating on a lot more data. This is not necessary to ensure the functionality these tests are trying to protect, and in the interest of speed operating on less data saves around 10min when running the tests on my local machine.
> [verify/nn/train] Attempt to speed up mnist tests.

- src/cortex/nn/execute.clj
For a big benefit in speed and a small benefit in space, these should default to :float.
> [execute] Default train/run contexts `:float` instead of `:double`.

- src/cortex/nn/execute.clj
- src/cortex/verify/nn/train.clj
- test/clj/cortex/compute/nn/cuda_train_test.clj
- test/clj/cortex/compute/nn/train_test.clj
These counts matching precisely doesn't really matter. The (indirect) call to `partition` in `train` quantizes the inference-count to be a multiple of the batch-size while leaving the dataset-count alone.
Tests still pass, and I verified this works with a couple of models I've been training that I'd accounted for this outside (by ensuring that my batch size divided my dataset size evenly). With this change they still work without those outside hacks.
> [nn/execute] Spurious throw in `execute-loss-term`.

- test/clj/cortex/loss_test.clj
A defect in core.matrix was making this test fail, but that defect is fixed now.
> [cortex/loss-test] Un-comment out this test.

- examples/docker-example/src/docker_example/core.clj
- experiment/src/cortex/experiment/train.clj
- src/cortex/dataset.clj
- src/cortex/datasets/mnist.clj
- src/cortex/datasets/util.clj
- src/cortex/nn/execute.clj
- src/cortex/util.cljc
- src/cortex/verify/nn/train.clj
- test/clj/cortex/datasets/math_test.clj
- test/clj/cortex/nn/traverse_test.clj
Some of the code in `datasets/util` was not really dataset specific and so can be safely moved to `cortex/util`.
What remains in `dataset.clj`, `datasets/mnist.clj`, and `datasets/util.clj` is now much closer to minimal, and represents good practices around utility datasets for testing and verification as well as basic information for users about datasets in general.
> [dataset] Promote some code to util.

- examples/mnist-classification/src/mnist_classification/core.clj
- experiment/src/cortex/experiment/util.clj
- src/cortex/util.cljc
- test/cljc/cortex/util_test.cljc
This fixes up a couple of assumptions in the experiment machinery that class names will be numbers, and such (they are in mnist, but not in general). The class-mapping is a better way to handle this.
Also added some error handling and tests to util/idx->one-hot.
> [experiment] Classification bug fixes.

- src/cortex/nn/compute_binding.clj
- src/cortex/verify/nn/train.clj
Intermittent failures only on the cpu branch.  Problems could be in the stream event sync mechanism or in the parallel library or just in one bit of lazy code.
> Trying to get to the bottom of the unit test oddities

- experiment/src/cortex/experiment/util.clj
Add optional :colorspace key in cortex.experiment.util that threads through to think.image.patch/image->patch.  
Colorspace had been set to :gray in cortex.experiment.util, so that is kept as the default value.  However it may be desireable in the future to set the default to :rgb since that is the the default in think.image.patch.
> Thread colorspace from experiment to think.image.patch

- CHANGELOG.md
- importers/model-upgrader/README.md
- importers/model-upgrader/project.clj
- importers/model-upgrader/src/model_upgrader/core.clj
- src/cortex/compute/math.clj
- src/cortex/compute/nn/backend.clj
- src/cortex/nn/compute_binding.clj
We were just hit by an upgrade to core matrix that destroyed all old nippy files.  The solution is to avoid saving any library-specific types into the file but still save datastructures that are (barely) core matrix compatible.
To be clear, the upgrade was in the base mikera vectorz java library not in core.matrix.  We had been storing the vectorz types in the network save format.
> Save format that only includes pure java types.

- src/cortex/compute/cpu/backend.clj
"or" syntax was incorrect.  For consistency, I just moved datatype into the let binding instead of changing it to {datatype :double}.
> minor bug fix

- src/cortex/buffer_initialization.clj
- src/cortex/nn/layers.clj
- test/clj/cortex/nn/network_test.clj
Added option to specify weight initialization by random orthogonal vectors instead of just random vectors.  To use, add ":weights {:initialization {:type :orthogonal}}" to any layer.
I expected this to improve training in the early epochs, but after many configurations on cifar-10 data, I did not find it to perform better than He-normal initialization.  Maybe someone else will find it a useful option.
> Add orthogonal weight initialization

- examples/mnist-classification/src/mnist_classification/core.clj
- examples/mnist-classification/src/mnist_classification/main.clj
- experiment/project.clj
- experiment/src/cortex/experiment/classification.clj
Hi all,
I've added support to view the weights of layers using tensorboard's histograms and distributions. 
The changes in this PR 
- Using [tfevent-sink](https://github.com/shark8me/tfevent-sink) to write both scalars (such as accuracy or loss) and buffers/weights to a Tensorflow Event Record format log file.
- Updated the examples/mnist-classification to accept generic listeners
- capability to test tensorflow outputs using a "-t logfile" argument to the "lein run" command. With no arguments, the existing listener is used.
I would like to hear feedback about the listener API. I refactored the existing API a bit to create listeners may not be image-focused and could accept any necessary arguments.
> Support for viewing weights in Tensorboard

- experiment/src/cortex/experiment/util.clj
- experiment/test/cortex/experiment/util_test.clj
This adds a general function in experiment/util.clj to make datasets infinite for the train-n function, which can be used for both regression and classification. You can't exactly rewrite infinite-class-balanced-dataset based on this function directly (you would have to refactor common code into a separate function, and it's just two lines so I'm not sure it's worth it).
> Add function to make infinite datasets for regression and classification

- experiment/src/cortex/experiment/util.clj
- experiment/test/cortex/experiment/util_test.clj
Introduces a high-level data preprocessing function called "one-hot-encoding," which takes a dataset and a list of categorical features (i.e. data that takes on discrete values that are not numeric in nature, and as such cannot be fed into an ML algorithm) and performs one-hot encoding of the data. Modeled off of https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html. Should be useful for all sorts of non-image datasets.
> Data encoding

- experiment/src/cortex/experiment/classification.clj
- experiment/test/cortex/experiment/tensorboard_test.clj
The perform-experiment API calls the train-forever method, but did not optional allow arguments (such as force-gpu?) to be passed to the train-forever method. 
I changed the API to take a (optional) map containing arguments which is then passed to the train-forever method.  
I also added a test that calls the perform-experiment API with optional arguments.
>  enable passing arguments to perform-experiment API

- examples/catsdogs-classification/project.clj
- examples/catsdogs-classification/src/catsdogs/training.clj
- examples/docker-example/project.clj
- examples/mnist-classification/project.clj
- examples/mnist-classification/src/mnist_classification/core.clj
- examples/optimise/project.clj
- examples/visualization/project.clj
- experiment/project.clj
- importers/caffe/project.clj
- importers/keras/project.clj
- importers/model-upgrader/project.clj
- project.clj
Updating to clojure 1.9
Requires a small update in think.image https://github.com/thinktopic/think.image/pull/10 - once the pull request is merged, the version numbers in this pull request can be updated.
Tested all the examples and they seem to work fine.
The only area that I didn't test, because I don't have all the local deps, are the importers. They would still need to be checked out
> Update to clojure 1.9

- examples/xor-mlp/src/xor_mlp/core.clj
Noticed these calls to `execute/run` were referencing unbound `xor` instead of `xor-dataset`.
```
xor-mlp.core=> (train-xor)
IllegalStateException Attempting to call unbound fn: #'xor-mlp.core/train-xor  clojure.lang.Var$Unbound.throwArity (Var.java:43)
```
> rename var xor -> xor-dataset

- project.clj
- src/cortex/compute/array_view_math.clj
- src/cortex/compute/cpu/backend.clj
- src/cortex/compute/cpu/driver.clj
- src/cortex/compute/cpu/tensor_math.clj
- src/cortex/compute/cuda/backend.clj
- src/cortex/compute/cuda/driver.clj
- src/cortex/compute/javacpp_datatype.clj
- src/cortex/compute/math.clj
- src/cortex/compute/verify/driver.clj
- src/cortex/loss/center.clj
- src/cortex/nn/execute.clj
- src/cortex/optimize/adam.clj
- src/cortex/tensor.clj
- src/cortex/verify/nn/train.clj
- test/clj/cortex/compute/compute_loss_test.clj
- test/clj/cortex/compute/cpu_driver_test.clj
- test/clj/cortex/compute/nn/gradient_test.clj
- test/clj/cortex/compute/nn/layers_test.clj
Working back towards supporting clojurescript.  Also, however, the datatype library needed a major simplification pass.
Dropped CPU support for LRN layers.  This is better done with a convolution layer with kernel width,height of 1 and same number of kernels and input channels.
May attempt to re-engineer the LRN layer support using tensors later.  The GPU version still works and the tests are all still there just the cpu side of things is commented out.
> Upgrading to a minimized and slightly optimized datatype library.

- examples/mnist-classification/src/mnist_classification/core.clj
This modification will yield better training results for this example which I think is important to show to new comers to the project.
Here are the results on my computer with and without gpu, before and after the change:
```
Parameter count: 849780
Saving network to trained-network.nippy
Classification accuracy: 0.8026
Saving network to trained-network.nippy
Classification accuracy: 0.7925
Classification accuracy: 0.7751
Classification accuracy: 0.7625
Classification accuracy: 0.7672
Classification accuracy: 0.7555
Classification accuracy: 0.7595
Classification accuracy: 0.7655
Classification accuracy: 0.7707
Classification accuracy: 0.7767
Classification accuracy: 0.7765
Classification accuracy: 0.778
Classification accuracy: 0.7961
Classification accuracy: 0.7854
Classification …
```
> Tweak MNIST example to get rid of first dropout layer

- experiment/project.clj
- experiment/src/cortex/experiment/classification.clj
- experiment/src/cortex/experiment/train.clj
* supports a train and test loss, available for the train-forever as well as for tensorboard listener
* tensorboard listener takes an additional argument metric-fn that could accepts actual and predicted labels. It can be used to calculate metrics such as f1 scores/precision/recall, both average and per-class.
> Support for train and test loss metrics via the experiment API

- README.md
cuda in caskroom/driver has already [renamed to nvidia-cuda since Oct 22](https://github.com/caskroom/homebrew-drivers/commit/f56e9ab9b8e2865e7c5965d014bcaa06ed196f19#diff-f9032f896f3316d57d071c60b61fa9c6). This PR update the cuda installation instruction to keep it up to the change mentioned.
#252
> Update brew cuda installation instruction
